### PR TITLE
feat(repo): add support for conventional commits

### PR DESCRIPTION
**Pull request by jsonberry**

### CODE REVIEW

**Comment by jsonberry** [comment]
@Fallenstedt 

This merge introduces support for [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.2/).

The repo would now requires commit messages to fit the conventional commits spec, this is done by using:

- [commitlint](https://github.com/marionebl/commitlint)
- [husky](https://github.com/typicode/husky)
- [commitizen](https://github.com/commitizen/cz-cli)

Overall this is very easy to use, the commit messages need to match something like this:
```
feat(web): add toast service
```

Commitzen adds a CLI utility for writing out the messages, just `npm run cm` and it will start the CLI, you can choose the options you want and add your message.

**Comment by jsonberry** [comment]
You're not required to use the CLI or anything you can just write commit messages yourself, they'll just get linted and have to match the spec. One way I like to write them is like this:
```
feat(web): add toast service
```

I start with something like that and I keep doing more work, and when I get more work done I ammend the commit, like this:
```
git add .
git commit --amend
```

Then I adjust the message and add work to the body of the commit:
```

* add toast components
* add new service
* add tests

closes #123
```
Where each line in the body was some work i did, and the footer would auto close an open GitHub issue once the MR is merged

**Comment by Fallenstedt** [comment]
This sounds amazing. I wish I knew about this sooner. 💸💅💸

**Comment by jsonberry** [comment]
It's pretty great.

It can, and should, get used with projects like this:
https://github.com/conventional-changelog/conventional-changelog
https://github.com/conventional-changelog/standard-version

These are _to die for_, but I'm not gonna put them in this project for now, no need for them here yet.

Here's an example of using `conventional commit` and generating a changelog with `standard version` and `conventional changelog`: https://github.com/jsonberry/rxjs-toolkit/blob/master/CHANGELOG.md

**Pull request merged**
